# Yogo Data Management Toolkit
# Copyright (c) 2010 Montana State University
#
# License -> see license.txt
#
# FILE: database.yml.start
#
#
development:
  adapter: persevere
  versioned: true
  host: localhost
  path: '/persevere'
  port: 8400

production:
  adapter: persevere
  versioned: true
  host: localhost
  path: '/persevere'
  port: 8400

# run with bin/persvr -p 8081
test: &TEST
  adapter: persevere
  versioned: true
  host: localhost
  path: '/persevere_test'
  port: 8400

cucumber:
  <<: *TEST
