# Yogo Data Management Toolkit
# Copyright (c) 2010 Montana State University
#
# License -> see license.txt
#
# FILE: database.yml.start
#
#

development:
  adapter: sqlite3
  database: db/development.sqlite3

production:
  adapter: sqlite3
  database: db/production.sqlite3

test:
  adapter: sqlite3
  database: db/test.sqlite3

yogo_development:
  adapter: persevere
  versioned: true
  host: localhost
  port: 8080

yogo_production:
  adapter: persevere
  versioned: true
  host: localhost
  port: 8080

# run with bin/persvr -p 8081
yogo_test: &YOGO_TEST
  adapter: persevere
  versioned: true
  host: localhost
  port: 8081

yogo_cucumber:
  <<: *YOGO_TEST
