# Yogo Data Management Toolkit
# Copyright (c) 2010 Montana State University
#
# License -> see license.txt
#
# FILE: database.yml.start
#
#

development:
  adapter: sqlite3
  database: db/sqlite3/development.sqlite3

production:
  adapter: sqlite3
  database: db/sqlite3/production.sqlite3

test:
  adapter: sqlite3
  database: db/sqlite3/test.sqlite3

#
# HIS Servers
#
his:
  adapter: rest
  format: xml
  host: voeis.msu.montana.edu
  port: 4000
